fix: typing_extensions needed for @deprecated up until python 3.12 (#231)
We need to use `typing_extensions` for python 3.12, as the [`deprecated`
decorator wasn't added until python
3.13](https://docs.python.org/3/library/warnings.html#warnings.deprecated).
This causes import issues when using fgpyo on python 3.12 or above.

```console
Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    from fgpyo.sam import Cigar
  File "/path/to/python3.12/site-packages/fgpyo/sam/__init__.py", line 183, in <module>
    from typing_extensions import Self
ModuleNotFoundError: No module named 'typing_extensions'
```